import videos from "../../dummydata"
import Video from "./ui/Video"

export default function FeaturedVideos() {
    console.log(videos)
    return (
        <div className="px-4 md:px-6 lg:px-10">
            <h1 className="font-bold text-lg md:text-xl lg:text-2xl">Featured Videos</h1>
            <p className="font-semibold text-sm md:text-base lg:text-lg" style={{ color: "var(--text-secondary)" }}>
                Popular Visualizations Generated by our Community
            </p>
             <p className="font-semibold text-sm md:text-base lg:text-lg" style={{ color: "var(--text-secondary)" }}>
                Popular Visualizations Generated by our Community
            </p> 
            
            <div className="videos w-full flex flex-col sm:flex-row  gap-4 justify-center md:gap-5 mt-4">
                {videos.map((vid) => (
                    <div className="w-full sm:w-1/2 md:w-1/3 lg:w-1/4" key={vid.videoId}>
                        <Video video={vid} />
                    </div>
                ))}
            </div>
        </div>
    )
}
