import { FaArrowLeft } from "react-icons/fa"
import videos from "../../dummydata"
import Video from "./ui/Video"
import { MoveRight } from "lucide-react"
import { Link } from "react-router-dom"

export default function FeaturedVideos() {
    const top_videos = videos.slice(0,3)
    return (
        <div className="">
           <div className="flex sm:px-[13em] justify-between md:gap-5">
                <div className="side">
                    <h1 className="font-bold text-lg md:text-xl lg:text-2xl">Featured Videos</h1>
                    <p className="font-semibold text-sm md:text-base lg:text-lg" style={{ color: "var(--text-secondary)" }}>
                        Popular Visualizations Generated by our Community
                    </p>
                </div>

                <Link to={"/community-videos"}><p className="font-semibold hover:text-hover text-sm md:text-base lg:text-lg flex items-center justify-center gap-5 text-secondary"> see more <MoveRight/></p></Link>
            </div>
            <div className="videos flex flex-col sm:flex-row gap-4 justify-center md:gap-5 mt-4">
                {top_videos.map((vid) => (
                    <div className="w-full sm:w-1/2 md:w-1/3 lg:w-1/4" key={vid.videoId}>
                        <Video video={vid} />
                    </div>
                ))}
            </div>
        </div>
    )
}
